### PR TITLE
Move baseline tests to project root

### LINKED ISSUE #36: Move baseline output tests to project root/base directory
## Issue checklist
_Put an `x` in all the boxes that apply_

- [x] I have read the [README](https://github.com/NOAA-GSL/SENA-c_sw/blob/develop/README.md) and [ref/README](https://github.com/NOAA-GSL/SENA-c_sw/blob/develop/ref/README.md), including the Troubleshooting Guide.
- [x] I have reviewed existing issues to ensure this has not already been reported.

### I am submitting a ...

Put an `x` in the appropriate box

- [x] Suggestion for improving existing code or documentation
- [ ] Documentation error

### The problem

Move baseline output tests ( `ref/test/test_output/` ) into project root, and update `ref/test/CMakeLists.txt` to point to the new location. 

With addition implementations of the kernel, the baseline tests should live outside of the ref/ directory.

### PR DESCRIPTION
**Pull request by robgpita**
## Proposed changes

For future language implementations, the baseline tests need to be in the SENA-c_sw root directory.  This PR closes #36. Move baseline tests ( `ref/test/test_output/` ) into project root directory, and update `ref/test/CMakeLists.txt` to account for this change in location.

## Types of changes

What types of changes does your code introduce?

- [x] Bugfix (Change which fixes an issue)
- [ ] New feature (Change which adds functionality)
- [x] Enhancement to existing functionality (non-breaking change which improves existing code or documentation)
- [ ] Breaking change (fix or feature that changes results and requires updates to test baselines)
- [x] Documentation Update

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/NOAA-GSL/SENA-c_sw/blob/develop/CONTRIBUTING.md) document
- [x] I have ensured all my changes contribute to a common purpose
- [x] I have verified my change does not add debug code
- [x] I have verified my change does not add code that is commented out
- [x] I have verified unit tests pass locally with my changes
- [x] I have verified my changes adhere to style guidelines
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by LyndStringer — DISMISSED** [review]
All the tests passed.  This is a good foundational change for the future Julia directory.

**Review by christopherwharrop-noaa — CHANGES_REQUESTED** [review]
This work looks good.  My only request is to better consolidate the location of the input data and test baselines.  What I propose is a top-level `test` directory that includes both the input data and the test baselines.  Maybe something like:

```
test/
test/data
test/data/input
test/data/output
test/baselines
```

This would keep the top-level a bit cleaner.

**Comment by robgpita** [comment]
@christopherwharrop-noaa I agree, placing data/ and baselines/ directories into a top level test/ directory is cleaner.

**Review by christopherwharrop-noaa — APPROVED** [review]
Thank you for the update.

**Pull request merged**
