### PR TITLE
Update open_file subroutine to create NetCDF files in NETCDF4 format

### LINKED ISSUE #19: NetCDF files are written in CDF-1 classic format
The current code writes NetCDF output in CDF-1 classic format.  This format limits the size of files to 2GB.  While 2GB files are sufficient for current needs, upcoming scaling of input data will require file sizes beyond 2GB.  Moving to NetCDF4 format will fix this problem.

### PR DESCRIPTION
**Pull request by robgpita**
Closes #19.

### CODE REVIEW

**Review by LyndStringer — DISMISSED** [review]
Does this fix an issue?

**Comment by christopherwharrop-noaa** [comment]
> Does this fix an issue?

It does now.  I linked the issue in the description, and when this PR is merged, the issue will automatically be closed.

**Comment by christopherwharrop-noaa** [comment]
@robgonzalezpita - It looks like this PR includes commits from previous updates.  Can you please redo this PR so that it only includes the new commits that address the NetCDF issue?  A good practice when starting work on a new feature or bug fix is to make sure your `develop` is up-to-date and then create the new branch from that.

```
git checkout develop
git fetch -p
git pull
git checkout -b feature/new-feature
<do your work with one or more git add/commit>
git push origin feature/new-feature
```

**Comment by christopherwharrop-noaa** [comment]
@robgonzalezpita - The `ci.yml` still seems to contain the install of the gfortran for the MacOS build.

**Pull request closed without merging**
