### PR TITLE
Reduced code size by removing the nested option which was controlled …

### PR DESCRIPTION
**Pull request by middlecoff**
## Proposed changes

Reduced code size by removing the nested option which was controlled by the hardwired parameter:
```
logical, parameter :: nested = .false.
```
## Types of changes

What types of changes does your code introduce?
_Put an `x` in all the boxes that apply_

- [x] Enhancement to existing functionality (non-breaking change which improves existing code or documentation)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/NOAA-GSL/SENA-c_sw/blob/develop/CONTRIBUTING.md) document
- [x] I have ensured all my changes contribute to a common purpose
- [x] I have verified my change does not add debug code
- [x] I have verified my change does not add code that is commented out
- [x] I have verified unit tests pass locally with my changes
- [x] I have verified my changes adhere to style guidelines

### CODE REVIEW

**Comment by christopherwharrop-noaa** [comment]
@middlecoff - Please edit the description of this PR in the "Proposed Changes" section to address the prompts in the template.  Replace the prompts will your response to those prompts.  Remove prompts that do not apply.

**Review by christopherwharrop-noaa — COMMENTED** [review]
The code changes correctly address the removal of the "nested" option.  As soon as the description section of this PR is updated I will approve and merge.

**Comment by middlecoff** [comment]
How do I do that? When I submitted it I checked some of the boxes, now what do I do?

**Comment by christopherwharrop-noaa** [comment]
@middlecoff - Please do not use email to respond to Github comments.  Use the Github interface instead.

You need to edit the description by clicking on the three dots in the upper-right corner of the initial comment showing this PRs description.  Select "edit" and then replace the text with the answers to the prompts.

**Review by LyndStringer — APPROVED** [review]
Just a focus on nested, not grid_type.  I'm assuming grid_type is next, yes?

**Review by robgpita — APPROVED** [review]
@middlecoff Thanks for removing the `nested` option, which was not in use.

**Comment by middlecoff** [comment]
Sorry for being so dense, but do reviewers not see the answers to the
prompts?

**Comment by middlecoff** [comment]
Yes, grid_type is next.

**Comment by christopherwharrop-noaa** [comment]
@middlecoff  - Please stop using email to respond to Github PR comments.  Use the Github interface instead.

Go to Github and look at the pull request.  You will see that the description looks like this:




…by the hardwired parameter:

logical, parameter :: nested = .false.

## Proposed changes
Describe the big picture of your changes here to communicate what they accomplish and why this pull request should be accepted.

If it fixes a bug or resolves a feature request, be sure to link to that issue.

If it depends on other pull requests, be sure to list and link those dependencies.

**Review by christopherwharrop-noaa — APPROVED** [review]

**Pull request merged**
